
version: '3'
services:
  drupal:
    image: drupal:latest
    ports:
      - "81:80"
    volumes:
      - volumenDocker:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      APACHE_SERVER_NAME: localhost
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - volumenDocker:/var/lib/minesql

    restart: always

volumes:
  volumenDocker:






